### ISSUE TITLE
Startseite überarbeiten

### ISSUE THREAD

**Issue by dorianim** [Eistbaren/client#102]

**Comment by LadnerJonas** [comment]
Die Startseite ist so schon schön genug. Kulturbanausen, die sowas nicht zu schätzen wissen, möchten wir nicht als Kunden haben.

**Comment by 16flotho** [comment]
Holy shit... Wer das gutheißen kann, gehört auf den Mond geschossen

**Comment by 16flotho** [comment]
Nur so...
