### ISSUE TITLE
Missing imprint

### ISSUE THREAD

**Issue by LadnerJonas** [Eistbaren/client#107]
![image](https://user-images.githubusercontent.com/92096842/179317504-7ee70bee-c4c7-42c3-8f48-271ddc6bb16c.png)

**Comment by dorianim** [comment]
Was soll den da rein in den Imprint? Irgendso rechtlicher Kram wegen Datenschutz?

**Comment by LadnerJonas** [comment]
@dorianim Joa zumindest irgendwas sollte schon kommen, wenn wir den Butten behalten möchten.

**Comment by dorianim** [comment]
hmmmmmmmmmmmm
