### ISSUE TITLE
Reserved tables blocked on == timestamp

### ISSUE THREAD

**Issue by mariusdkm** [Eistbaren/client#120]
Should tables be free at the minute the reservation ends?

**Comment by dorianim** [comment]
@mariusdkm passt das jetzt? Weiß nich mehr genau, was die Issue bedeutet.

**Comment by mariusdkm** [comment]
Nope, das issue ist noch nicht gefixed

**Comment by LadnerJonas** [comment]
Das sollte man, denke ich, serverseitig fixen

**Comment by LadnerJonas** [comment]
Okay ich verstehe doch nicht, was der Issue macht @mariusdkm
