### ISSUE TITLE
Floor plan is not rendered correctly

### ISSUE THREAD

**Issue by LadnerJonas** [Eistbaren/client#68]
@dorianim ist das so geplant, oder läuft da was schief?
![image](https://user-images.githubusercontent.com/92096842/177015836-74952b20-28f0-484d-8b00-24de8e0b4ab3.png)

**Comment by dorianim** [comment]
Liegt dran, dass die pr noch nich gemerged ist. https://github.com/Eistbaren/server/pull/120

Sobald die drin ist, sollts gehen :)

**Comment by LadnerJonas** [comment]
Oh ja, das ergibt Sinn :+1:

**Comment by dorianim** [comment]
![Screenshot_2022-07-03-09-57-34-75_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/30153207/177030698-f1896d3e-6daf-4677-9f9e-355e47c48f35.jpg)

Jetzt läufts
