### ISSUE TITLE
Summary Page Design bug

### ISSUE THREAD

**Issue by LadnerJonas** [Eistbaren/client#70]
![image](https://user-images.githubusercontent.com/92096842/177032758-613ea25b-07f5-4472-89d1-1cbad02adcc7.png)
bzw.
![image](https://user-images.githubusercontent.com/92096842/177032794-6664241f-ff18-4e16-b40c-ef5a2c0d53e3.png)

Download ICS-File ist auch noch etwas buggy

**Comment by dorianim** [comment]
Fixed
